name: Hybrid JMeter Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight GMT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  LocalTest:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Local JMeter Tests
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: jmeter-files/local-test-plan.jmx
          args: ""

      - name: Upload Local Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-local-results
          path: local-result.jtl

  ScheduledTest:
    runs-on: ubuntu-latest
    needs: LocalTest
    strategy:
      matrix:
        scheduled-run:
          - true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run AWS JMeter Tests
        if: matrix.scheduled-run
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: jmeter-files/aws-test-plan.jmx
          args: ""

      - name: Upload AWS Results
        if: matrix.scheduled-run
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-aws-results
          path: aws-result.jtl
