on: [push]

jobs:
  Main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Download JMeter
        run: |
          curl -L https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz | tar xz
          export JMETER_HOME=$PWD/apache-jmeter-5.4.1
          export PATH=$PATH:$JMETER_HOME/bin

      - name: Run JMeter Tests
        run: jmeter -n -t jmeter-files/test-plan.jmx -l result.jtl

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl